sudo: required
services:
  - docker
env:
  global:
    - REPO_NAME=hugomcfonseca/rundeck-alpine
    - VERSION=2.10.8

before_script:
  - docker pull "$REPO_NAME" || true
script:
  - docker build --pull --cache-from "$REPO_NAME" --target=basic  --tag "$REPO_NAME:${VERSION}-basic" .
  - docker build --pull --cache-from "$REPO_NAME" --target=templated  --tag "$REPO_NAME:${VERSION}-templated" .
  - docker build --pull --cache-from "$REPO_NAME" --target=production  --tag "$REPO_NAME:${VERSION}" .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag "$REPO_NAME:${VERSION}" "${REPO_NAME}:latest"
deploy:
  provider: script
  script: docker push ${REPO_NAME}:${VERSION}-basic ${REPO_NAME}:${VERSION}-templated ${REPO_NAME}:${VERSION} ${REPO_NAME}:latest
  on:
branch: issue/9
