[template]
src = "etc/rundeck/framework.properties"
dest = "/etc/rundeck/framework.properties"
owner = "rundeck"
keys = [
    "/admin/user",
    "/admin/password",
    "/rd/base",
    "/rd/config",
    "/rd/host",
    "/rd/port",
    "/rd/ssl/enabled",
    "/ssh/user"
]
